repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black-jupyter
        args:
          - --line-length=88
          - --include='\.pyi?$'

          # these folders wont be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|
            _build|
            buck-out|
            build|
            dist"""
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1 # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
